<?php
/**
 * @file
 * Text format filter to convert the word "cat" into a link to a cat image.
 */
  
 /**
  * Implements hook_filter_info()
  *
  * https://api.drupal.org/api/drupal/modules!filter!filter.api.php/function/hook_filter_info/7
  */
function hellokitty_filter_info() {
    $filters = array();
    $filters ['hellokitty'] = array(
        'title' => t('Make each occurrence of "cat" a link to a cat photo '),
	'process callback' => '_hellokitty_filter',
	'cache' => FALSE,  /* Turn off caching during development. */
    );
    return $filters;
}

/**
 * 'process callback' for hellokitty_filter to carry out the string replacements.
 */
function _hellokitty_filter($text, $filter, $format, $langcode, $cache, $cache_id) {
    $pattern = '/(\bcat\b)/i';
    $replacement = '<a href="http://www.austintexas.gov/sites/default/files/files/Animal_Services/cute-kitten-playing.jpg">${1}</a>';
    
    return _hellokitty_do_replacements($text, $pattern, $replacement);
}

/**
 * Implements an algorithm to do string replacements in an HTML snippet.
 *
 * This implementation is a tongue in cheek attempt to produce something useful. 
 *
 * First, it does a simplistic string replacement in the entire html snippet. 
 * Then it does a simplistic string replacement in the snippet after all html has been stripped. 
 * The two counts for the number of replacements are compared. 
 * If the counts are equal, that means the presence of html tags did not affect 
 * the number of replacements and we can treat the simplistic string replacement as correct.
 *
 * On the other hand, if the counts are not equal, then there was at least one match within
 * an html tag. So we scrub the process and just pass back the original text unchanged.
 */
function _hellokitty_do_replacements($text, $pattern, $replacement) {
    $replace_no_limit = -1;

    $count_with_tags = NULL;
    $count_no_tags = NULL;
    
    $text_with_tags = preg_replace($pattern, $replacement, $text, $replace_no_limit, $count_with_tags);
    
    $text_no_tags = strip_tags($text);
    $text_no_tags = preg_replace($pattern, $replacement, $text_no_tags, $replace_no_limit, $count_no_tags);
    
    //~ dpm("count_no_tags is $count_no_tags");
    //~ dpm("count_with_tags is $count_with_tags");
    
    return ($count_with_tags == $count_no_tags) ? $text_with_tags : $text;
}